### model
model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
aligned_model: agentica-org/DeepScaleR-1.5B-Preview

### method
stage: dpo
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_config.json

pref_beta: 1.5
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]
### dataset
dataset: open-r1-long-cot-pair
template: deepseek
cutoff_len: 8192
max_samples: 268694
overwrite_cache: true
preprocessing_num_workers: 16


### output
output_dir: DeepSeek-R1_models/DeepSeek-R1-7B-beta-1.5
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 2.0e-5
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.001
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100